# 1. <a id='toc1_'></a>[Foundational Python for Data Science - Kennedy Behrman](#toc0_)

**Table of contents**<a id='toc0_'></a>    
- 1. [Foundational Python for Data Science](#toc1_)    
  - 1.1. [Capítulo 07: NumPy](#toc1_1_)    
  - 1.2. [Capítulo 08: SciPy](#toc1_2_)    
  - 1.3. [Capítulo 09: Pandas](#toc1_3_)    
  - 1.4. [Capítulo 10: Visualization Libraries](#toc1_4_)    
  - 1.5. [Capítulo 11: Machine Learning Libraries](#toc1_5_)    
  - 1.6. [Capítulo 12: Natural Language Toolkit](#toc1_6_)    
  - 1.7. [Capítulo 13: Functional Programming](#toc1_7_)    
  - 1.8. [Capítulo 14: Object-Oriented Programming](#toc1_8_)    
  - 1.9. [Capítulo 15: Other Topics](#toc1_9_)    

<!-- vscode-jupyter-toc-config
	numbering=true
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

## 1.1. <a id='toc1_1_'></a>[Capítulo 07: NumPy](#toc0_)

In [1]:
import numpy as np

In [2]:
type(np.array(['a', 'b']))

numpy.ndarray

In [3]:
np.empty(4)

array([2.12199579e-314, 0.00000000e+000, 5.35567160e-321, 1.22651357e-311])

In [4]:
np.arange(4)

array([0, 1, 2, 3])

In [5]:
oned = np.arange(12)
print(oned)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
twod = oned.reshape([3,4]) #Linhas por colunas
print(twod)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
only_zeros = np.zeros(12)
print(only_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
print(only_zeros.reshape(2,2,3)) #Reformata o array em, neste caso, duas matrizes 2x3

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [9]:
print(oned.ndim) #Explicita o numero de dimensoes da array
print(twod.ndim)

1
2


In [10]:
oned[3]

3

In [11]:
print(twod)

print(f'Esta é a dimensão escolhida: {twod[1]}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Esta é a dimensão escolhida: [4 5 6 7]


In [12]:
print(twod)

print(f'Este é o elemento escolhida: {twod[1, 2]}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Este é o elemento escolhida: 6


In [13]:
print(twod)
twod[0, 0] = 198

print(f'O novo array agora é: {twod}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
O novo array agora é: [[198   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [14]:
oned*3 #Arrays unidimensionais são como os vetores do R

array([594,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33])

In [15]:
nome = np.array(['Bruno', 'Garcia', 'Piato'])
nome[2]

'Piato'

In [16]:
print(twod[0] + twod[1]) #Adicao
print(twod[0] - twod[1]) #Subtracao
print(twod[0] / twod[1]) #Divisao
print(twod[0] * twod[1]) #Multiplicacao

[202   6   8  10]
[194  -4  -4  -4]
[49.5         0.2         0.33333333  0.42857143]
[792   5  12  21]


In [17]:
print(len(oned))
print(oned[oned <= 3]) #Aplicando filtros condicionais|operadores logicos
print(len(oned[oned <= 3]))

12
[1 2 3]
3


In [18]:
twod.mean(axis=0) #Calcula a media no sentido das colunas

array([70.,  5.,  6.,  7.])

In [19]:
twod.mean(axis=1) #Calcula a media no sentido das linhas

array([51. ,  5.5,  9.5])

In [23]:
oned.dtype = 'int8' #Convertendo o tipo de dados dentro de um array
oned.dtype 

dtype('int8')

## 1.2. <a id='toc1_2_'></a>[Capítulo 08: SciPy](#toc0_)

## 1.3. <a id='toc1_3_'></a>[Capítulo 09: Pandas](#toc0_)

## 1.4. <a id='toc1_4_'></a>[Capítulo 10: Visualization Libraries](#toc0_)

## 1.5. <a id='toc1_5_'></a>[Capítulo 11: Machine Learning Libraries](#toc0_)

## 1.6. <a id='toc1_6_'></a>[Capítulo 12: Natural Language Toolkit](#toc0_)

## 1.7. <a id='toc1_7_'></a>[Capítulo 13: Functional Programming](#toc0_)

## 1.8. <a id='toc1_8_'></a>[Capítulo 14: Object-Oriented Programming](#toc0_)

## 1.9. <a id='toc1_9_'></a>[Capítulo 15: Other Topics](#toc0_)